---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: aerospike-node-001
    groups:
      - aerospike
      - mesh_cluster
    hostname: aerospike-node-001
    image: kishorv06/debian-systemd:10-slim
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    port_bindings:
      3000: 3000

  - name: aerospike-node-002
    groups:
      - aerospike
      - mesh_cluster
    hostname: aerospike-node-002
    image: kishorv06/debian-systemd:9-slim
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    port_bindings:
      3000: 3001

  - name: aerospike-node-003
    groups:
      - aerospike
      - mesh_cluster
    hostname: aerospike-node-003
    image: kishorv06/debian-systemd:10-slim
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    port_bindings:
      3000: 3002

  - name: aerospike-multicast-node
    groups:
      - aerospike
      - multicast
    hostname: aerospike-multicast-node
    image: kishorv06/debian-systemd:10-slim
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    port_bindings:
      3000: 3003

provisioner:
  name: ansible
  inventory:
    links:
      group_vars: tests/group_vars/

verifier:
  name: testinfra
